const fs = require('fs');

const files = [
  'src/pages/CentersTasks.tsx',
  'src/pages/AffiliatesTasks.tsx',
  'src/pages/AssistantSecGenTasks.tsx'
];

files.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');

  content = content.replace(
    'const [assignedTo, setAssignedTo] = useState("");\n  const [status, setStatus] = useState<"جديدة" | "جاري العمل عليها" | "متأخرة" | "منجزة">("جديدة");',
    'const [assignedTo, setAssignedTo] = useState("");\n  const [selectedAssignDept, setSelectedAssignDept] = useState("إدارة اللجان");\n  const [status, setStatus] = useState<"جديدة" | "جاري العمل عليها" | "متأخرة" | "منجزة">("جديدة");'
  );

  content = content.replace(
    '  const [employeesList, setEmployeesList] = useState<string[]>([\n    "مدير النظام"\n  ]);\n\n  useEffect(() => {\n    const q = query(collection(db, "employees"));\n    const unsubscribe = onSnapshot(q, (snapshot) => {\n      if (!snapshot.empty) {\n        let emps = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() as any }));\n        // Unconditionally hide sys admin and root users from all employee lists, regardless of current user role\n        emps = emps.filter(e => \n          e && \n          e.role !== "SYS_ADMIN" &&\n          e.id !== "01" && \n          e.name !== "شهاب الدين" && \n          e.email?.trim().toLowerCase() !== "khalafshehab@gmail.com" && \n          e.email?.trim().toLowerCase() !== "khalafshehab-crypto@gmail.com"\n        );\n        setEmployeesList(emps.map(e => e.name).filter(Boolean));\n      }\n    });\n    return () => unsubscribe();\n  }, []);',
    '  const [employeesList, setEmployeesList] = useState<string[]>([\n    "مدير النظام"\n  ]);\n  const [allEmployeesData, setAllEmployeesData] = useState<any[]>([]);\n\n  useEffect(() => {\n    const q = query(collection(db, "employees"));\n    const unsubscribe = onSnapshot(q, (snapshot) => {\n      if (!snapshot.empty) {\n        let emps = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() as any }));\n        // Unconditionally hide sys admin and root users from all employee lists, regardless of current user role\n        emps = emps.filter(e => \n          e && \n          e.role !== "SYS_ADMIN" &&\n          e.id !== "01" && \n          e.name !== "شهاب الدين" && \n          e.email?.trim().toLowerCase() !== "khalafshehab@gmail.com" && \n          e.email?.trim().toLowerCase() !== "khalafshehab-crypto@gmail.com"\n        );\n        setAllEmployeesData(emps);\n        setEmployeesList(emps.map(e => e.name).filter(Boolean));\n      }\n    });\n    return () => unsubscribe();\n  }, []);'
  );

  content = content.replace(
    'setAssignedBy(currentUserName);\n    setAssignedTo(employeesList[0] || "");',
    'setAssignedBy(currentUserName);\n    setSelectedAssignDept("إدارة اللجان");\n    const deptEmps = allEmployeesData.filter(emp => emp.orgLevel3 === "إدارة اللجان" || emp.orgLevel2 === "إدارة اللجان" || emp.orgLevel1 === "إدارة اللجان");\n    setAssignedTo(deptEmps.length > 0 ? deptEmps[0].name : (employeesList[0] || ""));'
  );

  content = content.replace(
    'setAssignedTo(task.assignedTo);\n    setStatus(task.status);',
    'setAssignedTo(task.assignedTo);\n    \n    // Find department of assignedTo\n    const emp = allEmployeesData.find(e => e.name === task.assignedTo);\n    if (emp && (emp.orgLevel3 || emp.orgLevel2 || emp.orgLevel1)) {\n      setSelectedAssignDept((emp.orgLevel3 || emp.orgLevel2 || emp.orgLevel1) as string);\n    } else {\n      setSelectedAssignDept("إدارة اللجان");\n    }\n\n    setStatus(task.status);'
  );

  content = content.replace(
    '                  {/* Assigned to */}\n                  <div>\n                    <label className="block text-xs font-black text-gray-750 mb-1">مسندة إلى (الموظف المكلف) *</label>\n                    <select\n                      value={assignedTo}\n                      onChange={(e) => setAssignedTo(e.target.value)}\n                      className="w-full p-2.5 bg-slate-50 border border-gray-300 rounded-xl text-xs font-black focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all"\n                    >\n                      {employeesList.map((e, i) => (\n                        <option key={i} value={e}>{e}</option>\n                      ))}\n                    </select>\n                  </div>',
    '                  {/* Assigned to */}\n                  <div className="space-y-2 lg:col-span-1">\n                    <label className="block text-xs font-black text-gray-750 mb-1">مسندة إلى (الموظف المكلف) *</label>\n                    <div className="flex flex-col gap-2">\n                      <select\n                        value={selectedAssignDept}\n                        onChange={(e) => {\n                          setSelectedAssignDept(e.target.value);\n                          const deptEmps = allEmployeesData.filter(emp => emp.orgLevel3 === e.target.value || emp.orgLevel2 === e.target.value || emp.orgLevel1 === e.target.value);\n                          if (deptEmps.length > 0) {\n                            setAssignedTo(deptEmps[0].name);\n                          } else {\n                            setAssignedTo("");\n                          }\n                        }}\n                        className="w-full p-2.5 bg-slate-50 border border-gray-300 rounded-xl text-xs font-black focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all"\n                      >\n                        {Array.from(new Set(allEmployeesData.map(e => e.orgLevel3 || e.orgLevel2 || e.orgLevel1).filter(Boolean))).map((dept, i) => (\n                          <option key={i} value={dept as string}>{dept as string}</option>\n                        ))}\n                      </select>\n                      <select\n                        value={assignedTo}\n                        onChange={(e) => setAssignedTo(e.target.value)}\n                        className="w-full p-2.5 bg-slate-50 border border-gray-300 rounded-xl text-xs font-black focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all"\n                      >\n                        {allEmployeesData.filter(emp => emp.orgLevel3 === selectedAssignDept || emp.orgLevel2 === selectedAssignDept || emp.orgLevel1 === selectedAssignDept).map((e, i) => (\n                          <option key={i} value={e.name}>{e.name}</option>\n                        ))}\n                      </select>\n                    </div>\n                  </div>'
  );

  content = content.replace(
    '                  {/* Assignee */}\n                  <div>\n                    <label className="block text-xs font-black text-gray-750 mb-1">الموظف المكلف</label>\n                    <select\n                      value={assignedTo}\n                      onChange={(e) => setAssignedTo(e.target.value)}\n                      className="w-full p-2.5 bg-slate-50 border border-gray-300 rounded-xl text-xs font-black focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all"\n                    >\n                      {employeesList.map((e, i) => (\n                        <option key={i} value={e}>{e}</option>\n                      ))}\n                    </select>\n                  </div>',
    '                  {/* Assignee */}\n                  <div className="space-y-2 lg:col-span-1">\n                    <label className="block text-xs font-black text-gray-750 mb-1">الموظف المكلف</label>\n                    <div className="flex flex-col gap-2">\n                      <select\n                        value={selectedAssignDept}\n                        onChange={(e) => {\n                          setSelectedAssignDept(e.target.value);\n                          const deptEmps = allEmployeesData.filter(emp => emp.orgLevel3 === e.target.value || emp.orgLevel2 === e.target.value || emp.orgLevel1 === e.target.value);\n                          if (deptEmps.length > 0) {\n                            setAssignedTo(deptEmps[0].name);\n                          } else {\n                            setAssignedTo("");\n                          }\n                        }}\n                        className="w-full p-2.5 bg-slate-50 border border-gray-300 rounded-xl text-xs font-black focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all"\n                      >\n                        {Array.from(new Set(allEmployeesData.map(e => e.orgLevel3 || e.orgLevel2 || e.orgLevel1).filter(Boolean))).map((dept, i) => (\n                          <option key={i} value={dept as string}>{dept as string}</option>\n                        ))}\n                      </select>\n                      <select\n                        value={assignedTo}\n                        onChange={(e) => setAssignedTo(e.target.value)}\n                        className="w-full p-2.5 bg-slate-50 border border-gray-300 rounded-xl text-xs font-black focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all"\n                      >\n                        {allEmployeesData.filter(emp => emp.orgLevel3 === selectedAssignDept || emp.orgLevel2 === selectedAssignDept || emp.orgLevel1 === selectedAssignDept).map((e, i) => (\n                          <option key={i} value={e.name}>{e.name}</option>\n                        ))}\n                      </select>\n                    </div>\n                  </div>'
  );

  fs.writeFileSync(file, content);
  console.log('Patched ' + file);
});
